name: FactionsPro+
author: xAndrei52
description: A Plugin For Easily Managing Factions For your server. !!
version: 1.3.20
main: FactionsPro\FactionMain
api: [3.0.0]
softdepend: ["AntiSpamPro"]
extensions: [sqlite3]
commands:
  f:
    description: use /f help for a list of commands.
    permission: f.command
permissions:
  f.command:
    default: true
    description: "Allow use of all faction commands"
